#MAJOR PROJECT

#Step 1: Importing Libraries

In [126]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#Step 2: Data Ingestion

In [127]:
df=pd.read_table("https://storage.googleapis.com/kagglesdsdata/datasets/9590/13660/fruit_data_with_colors.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20220804%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220804T085052Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=92a4b164f96d1c5b723d00185110b6c5691df2f4cf4c0390410000c0af03c55e6a05f147b2bfe97a976c406a57fb6ad4b62ebf0942f853d3d432e61656d6f30f2a5390a5d5052ef0bfab0ac5da1ff2d6d3e6eaa36d9a5ec7107864a38143207464359a0e5138884af7edbebb368300c839894ba6c94d0cd41a73689ce92587208036e5ad99e970fbaab81ccf57132468aea5dc8a3936c2da2fdee32e0d4bd839250bc64b5a2309259d6cedcfda1ad4b2e4c87d9896bffb3a0a8702d02a625e60cc14bf471bef2c02eb1cbcc0f1a25a15f0aef04f22f5eeef7522a8d8fba0c53e6da5061f53ca9746b72d023fbc3d4e75657b8142ecdfcf4a33ff64bd7350b63a")

In [128]:
df

fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    

#Step 3: Data Preprocessing

In [129]:
df.describe()

fruit_label        mass      width     height  color_score
count    59.000000   59.000000  59.000000  59.000000    59.000000
mean      2.542373  163.118644   7.105085   7.693220     0.762881
std       1.208048   55.018832   0.816938   1.361017     0.076857
min       1.000000   76.000000   5.800000   4.000000     0.550000
25%       1.000000  140.000000   6.600000   7.200000     0.720000
50%       3.000000  158.000000   7.200000   7.600000     0.750000
75%       4.000000  177.000000   7.500000   8.200000     0.810000
max       4.000000  362.000000   9.600000  10.500000     0.930000

In [130]:
df.columns

Index(['fruit_label', 'fruit_name', 'fruit_subtype', 'mass', 'width', 'height',
       'color_score'],
      dtype='object')

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fruit_label    59 non-null     int64  
 1   fruit_name     59 non-null     object 
 2   fruit_subtype  59 non-null     object 
 3   mass           59 non-null     int64  
 4   width          59 non-null     float64
 5   height         59 non-null     float64
 6   color_score    59 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 3.4+ KB


In [132]:
df.drop('fruit_subtype',axis='columns', inplace=True)#Because its of object datatype

In [133]:
df['fruit_name'].value_counts()

apple       19
orange      19
lemon       16
mandarin     5
Name: fruit_name, dtype: int64

In [134]:
df.replace({'fruit_name':{'apple':1,'lemon':1,'orange':2,'mandarin':2}},inplace=True)

In [135]:
df['fruit_name'].value_counts()

1    35
2    24
Name: fruit_name, dtype: int64

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   fruit_label  59 non-null     int64  
 1   fruit_name   59 non-null     int64  
 2   mass         59 non-null     int64  
 3   width        59 non-null     float64
 4   height       59 non-null     float64
 5   color_score  59 non-null     float64
dtypes: float64(3), int64(3)
memory usage: 2.9 KB


In [137]:
df.shape

(59, 6)

In [138]:
df.duplicated().sum()

0

In [139]:
df.isna().sum()

fruit_label    0
fruit_name     0
mass           0
width          0
height         0
color_score    0
dtype: int64

#Step 4: Data Visualisation

In [211]:
# sns.pairplot(df)

#Step 5: Define the independent variable X and dependent variable y

In [141]:
df.columns

Index(['fruit_label', 'fruit_name', 'mass', 'width', 'height', 'color_score'], dtype='object')

In [142]:
X=df.drop(['fruit_label'],axis=1)
# because X can not contain y and other 2 attributes are of object data type and are not needed

In [143]:
X.head()

fruit_name  mass  width  height  color_score
0           1   192    8.4     7.3         0.55
1           1   180    8.0     6.8         0.59
2           1   176    7.4     7.2         0.60
3           2    86    6.2     4.7         0.80
4           2    84    6.0     4.6         0.79

In [144]:
y=df['fruit_label'] #which is our categorical variable

In [145]:
y.head()

0    1
1    1
2    1
3    2
4    2
Name: fruit_label, dtype: int64

In [146]:
y.value_counts()

1    19
3    19
4    16
2     5
Name: fruit_label, dtype: int64

In [147]:
X.shape,y.shape

((59, 5), (59,))

#Step 6: Splitting dataset into train and test data

In [148]:
from sklearn.model_selection import train_test_split

In [149]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=2529)#since test size is given as 30%, train size is 70%

In [150]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((53, 5), (6, 5), (53,), (6,))

> If required we need to Scale the training data to reduce the impact of outliers

In [151]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

#Step 7: Modelling

In [152]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()#Logistic Regression Model

In [153]:
# from sklearn.neighbors import KNeighborsClassifier
# model=KNeighborsClassifier()#K-Nearest Neighbour Model

In [169]:
# from sklearn.tree import DecisionTreeClassifier
# model=DecisionTreeClassifier()#Decision Tree Model

In [184]:
# from sklearn.svm import SVC 
# model=SVC() #Support Vector Machine

In [198]:
# from sklearn.ensemble import RandomForestClassifier
# model=RandomForestClassifier()

#Step 8: Training Model

In [199]:
model.fit(X_train,y_train)

RandomForestClassifier()

#Step 9: Predicting Model

In [200]:
y_pred=model.predict(X_test)

In [201]:
y_pred

array([4, 4, 3, 3, 3, 3])

#Step 10: Accuracy

In [202]:
from sklearn.metrics import confusion_matrix, classification_report

In [203]:
confusion_matrix(y_test,y_pred)#confusion matrix is the best way to represent the accuracy of a Classification Model. It represents True Positives to False Negatives

array([[4, 0],
       [0, 2]])

In [204]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         2

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6



#__Future Predictions Example__

In [205]:
df_new=df.sample(1)#sample set

In [206]:
df_new

fruit_label  fruit_name  mass  width  height  color_score
57            4           1   152    6.5     8.5         0.72

In [207]:
X_new=df_new.drop(['fruit_label'],axis=1)

In [208]:
X_new.shape

(1, 5)

In [209]:
y_pred_new=model.predict(X_new)#sample prediction.

In [210]:
y_pred_new

array([4])

#Link of The same: https://colab.research.google.com/drive/1rNnpXeoMQ43C9Cd1Z6GKk6fdrUpTEGkA?usp=sharing